image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

install:
  - java -jar ./artifacts/app-ibank.jar -P:profile=test -port=9999 &

build_script:
  - chmod +x gradlew
  - ./gradlew build test --info "-Dselenide.headless=true"